---
- name: install required software
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - postfix
    - yum-cron
- name: start postfix
  service:
    name: postfix
    state: started
    enabled: yes
