---
- include: install-{{ ansible_distribution | lower }}.yml
- name: set hostname
  hostname:
    name: "{{ hostname }}"
- name: set up user accounts
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    state: present
  with_items: "{{ user_accounts }}"
- name: configure aliases
  lineinfile:
    dest: /etc/aliases
    line: "root:           {{ admin_email_address }}"
    regexp: "^#root:"
    backrefs: yes
  notify:
    - run newaliases
- name: configure yum-cron
  lineinfile:
    dest: /etc/yum/yum-cron.conf
    line: emit_via = email
    regexp: ^emit_via = stdio$
    backrefs: yes
  notify:
    - restart yum-cron
- name: start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - firewalld
    - yum-cron
- name: copy .toprc for root
  copy:
    src: .toprc
    dest: /root/
