---
- name: Set hostname
  tags: notest
  hostname:
    name: "{{ hostname }}"
  become: true
  notify: Reboot machine

- name: Set timezone
  tags: notest
  timezone:
    name: "{{ timezone }}"
  become: true
  notify: Reboot machine

- name: Make journal persistent
  file:
    path: /var/log/journal
    state: directory
  become: true
  notify: Reboot machine
  when: persistent_journal

- name: Install basic packages
  yum:
    name:
      - bash-completion
      - firewalld
      - mailx
      - postfix
  become: true

- name: Start and enable basic services
  tags: notest
  service:
    enabled: true
    name: "{{ item }}"
    state: started
  with_items:
    - firewalld
    - postfix
  become: true

- name: Configure root email alias
  lineinfile:
    insertafter: ^#root
    line: "root: {{ root_email_alias }}"
    path: /etc/aliases
    regexp: "^root:"
  become: true
  notify: Run newaliases command
  when: root_email_alias is defined

- name: Import ntp_client.yml
  import_tasks: ntp_client.yml
  when: ntp_client

- name: Import notify_updates.yml
  import_tasks: notify_updates.yml
  when: notify_updates
