---
- name: install required software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bash-completion
    - emacs
    - firewalld
    - iftop
    - iotop
    - mailx
    - postfix
    - python2-speedtest-cli
    - tree
    - yum-cron
  become: yes
- name: install VMware Tools
  package:
    name: open-vm-tools
    state: present
  when: vmware_tools
  become: yes
- name: set hostname
  hostname:
    name: "{{ hostname }}"
  become: yes
- name: set up user accounts
  user:
    name: "{{ item.login }}"
    groups: "{{ item.supplementary_groups }}"
    state: present
  with_items: "{{ shell_accounts }}"
  become: yes
- name: configure aliases
  lineinfile:
    dest: /etc/aliases
    line: "root:           {{ admin_email }}"
    regexp: "^#root:"
    backrefs: yes
  notify:
    - run newaliases
  become: yes
- name: configure yum-cron notifications
  lineinfile:
    dest: /etc/yum/yum-cron.conf
    line: emit_via = email
    regexp: ^emit_via = stdio$
    backrefs: yes
  notify:
    - restart yum-cron
  become: yes
- name: configure yum-cron auto-update
  lineinfile:
    dest: /etc/yum/yum-cron.conf
    line: apply_updates = yes
    regexp: ^apply_updates = no$
    backrefs: yes
  notify:
    - restart yum-cron
  when: auto_update
  become: yes
- name: start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - firewalld
    - postfix
    - yum-cron
  become: yes
