---
- name: Run newaliases command
  command: /usr/bin/newaliases
  become: true
  when: notest is not defined

- name: Restart yum-cron service
  service:
    name: yum-cron
    state: restarted
  become: true
  when: notest is not defined

- name: Reboot machine
  reboot:
  become: true
  when: notest is not defined
